### PR TITLE
Add -L$(LUA_LIBDIR) and $(LUA_LIB) to LIBS

### PR DESCRIPTION
**Pull request by lemniscati**
`LUA_LIBDIR` and `LUA_LIB` are defined in [`config`](https://github.com/lualdap/lualdap/blob/892ece82801f2b9d06f23525b6074c06e2a627bf/config#L6-L11), but not reflected in [`Makefile`](https://github.com/lualdap/lualdap/blob/892ece82801f2b9d06f23525b6074c06e2a627bf/Makefile#L36-L37).

### CODE REVIEW

**Comment by devurandom** [comment]
This should not be necessary, because the `lua` interpreter itself will already be linked against the library. Can you explain what problem you encountered that necessitated this change?

**Comment by lemniscati** [comment]
@devurandom Thank you for replying.

It seems to be necessary to specify libraries, in Cygwin.

I'm using Cygwin. And simple `make` causes undefined reference errors when making `src/lualdap.so`
```
gcc -O2 -fPIC -std=c89 -pedantic -Wall -W -Waggregate-return -Wcast-align -Wmissing-prototypes -Wnested-externs -Wshadow -Wwrite-strings  -I/usr/include/lua5.4 -I/usr/include -I/usr/include -DLUA_C89_NUMBERS   -c -o src/lualdap.o src/lualdap.c
gcc -O2 -fPIC -std=c89 -pedantic -Wall -W -Waggregate-return -Wcast-align -Wmissing-prototypes -Wnested-externs -Wshadow -Wwrite-strings  -o src/lualdap.so -shared   src/lualdap.o -L/usr/lib -lldap -L/usr/lib -llber
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x17): undefined reference to `luaL_checkudata'
src/lualdap.o:lualdap.c:(.text+0x17): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `luaL_checkudata'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x47): undefined reference to `lua_pushnumber'
src/lualdap.o:lualdap.c:(.text+0x47): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `lua_pushnumber'
...
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x1865): undefined reference to `luaL_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:45: src/lualdap.so] Error 1
```

But with this change, `make` does well:
```
gcc -O2 -fPIC -std=c89 -pedantic -Wall -W -Waggregate-return -Wcast-align -Wmissing-prototypes -Wnested-externs -Wshadow -Wwrite-strings  -I/usr/include/lua5.4 -I/usr/include -I/usr/include -DLUA_C89_NUMBERS   -c -o src/lualdap.o src/lualdap.c
gcc -O2 -fPIC -std=c89 -pedantic -Wall -W -Waggregate-return -Wcast-align -Wmissing-prototypes -Wnested-externs -Wshadow -Wwrite-strings  -o src/lualdap.so -shared   src/lualdap.o -L/usr/lib -llua5.4 -L/usr/lib -lldap -L/usr/lib -llber
```

Regards,
Lem

**Comment by lemniscati** [comment]
`LUA_LIB` and `LUA_LIBDIR` in `./config` look effective as configurable variables, but they are ignored in fact.
I think this situation is misleading, in my opinion.

A following additional patch will keep the original behavior almost
(doesn't specify `-llua*` as original, but specify a redundant `-L/usr/lib` ),
in case redundantly specifying libraries do any harm
(e.g. in a case, correct specification is different from ` -llua$(LUA_VERSION)` and not required to be specified).

```diff
--- a/config
+++ b/config
@@ -3,8 +3,8 @@ LUA := lua
 # Lua version number (first and second digits of target version)
 LUA_VERSION := $(shell $(LUA) -e 'print(_VERSION:match("%S+%s+(%S+)"))')
 
-# Lua library
-LUA_LIB = -llua$(LUA_VERSION)
+# Lua library (set LUA_LIB explicitly, if required)
+LUA_LIB = # -llua$(LUA_VERSION)
 # Lua library directory
 LUA_LIBDIR = /usr/lib
 # Lua include directory
```

**Comment by fperrad** [comment]
on the top of the `master` branch, the prefered way of building is via the rockspec with the following command:
```
luarocks make rockspec/lualdap-dev-2.rockspec
```

@lemniscati, is it work in Cygwin ?
Cygwin is a supported platform by Luarocks (see https://github.com/luarocks/luarocks/blob/master/src/luarocks/core/cfg.lua#L32-L50)

**Comment by lemniscati** [comment]
@fperrad No, it doesn't work, because `rockspec/lualdap-dev-2.rockspec` lacks settings for `-llber`. But this is another issue.
But '-llua*` is set correctly.

In cygwin, current `luarocks` needs to be fixed to work right. Following logs are by a fixed version of `luarocks`

```
$ luarocks-5.3 make rockspec/lualdap-dev-2.rockspec

lualdap dev-2 depends on lua >= 5.1 (5.3-1 provided by VM)
gcc -O2 -fPIC -I/usr/include/lua5.3 -c src/lualdap.c -o src/lualdap.o -I/usr/include
gcc -shared -o lualdap.so src/lualdap.o -L/usr/lib -Wl,-rpath,/usr/lib -lldap -L/usr/lib -llua5.3
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x2a7): undefined reference to `ber_str2bv'
src/lualdap.o:lualdap.c:(.text+0x2a7): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_str2bv'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x2e2): undefined reference to `ber_bvfree'
src/lualdap.o:lualdap.c:(.text+0x2e2): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_bvfree'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0xc6f): undefined reference to `ber_str2bv'
src/lualdap.o:lualdap.c:(.text+0xc6f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_str2bv'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0xcaa): undefined reference to `ber_bvfree'
src/lualdap.o:lualdap.c:(.text+0xcaa): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_bvfree'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x1222): undefined reference to `ber_free'
src/lualdap.o:lualdap.c:(.text+0x1222): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_free'
collect2: error: ld returned 1 exit status

Error: Build error: Failed compiling module lualdap.so
```

```
$ luarocks-5.4 make rockspec/lualdap-dev-2.rockspec

lualdap dev-2 depends on lua >= 5.1 (5.4-1 provided by VM)
gcc -O2 -fPIC -I/usr/include/lua5.4 -c src/lualdap.c -o src/lualdap.o -I/usr/include
gcc -shared -o lualdap.so src/lualdap.o -L/usr/lib -Wl,-rpath,/usr/lib -lldap -L/usr/lib -llua5.4
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x2ad): undefined reference to `ber_str2bv'
src/lualdap.o:lualdap.c:(.text+0x2ad): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_str2bv'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x2e8): undefined reference to `ber_bvfree'
src/lualdap.o:lualdap.c:(.text+0x2e8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_bvfree'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0xc7f): undefined reference to `ber_str2bv'
src/lualdap.o:lualdap.c:(.text+0xc7f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_str2bv'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0xcba): undefined reference to `ber_bvfree'
src/lualdap.o:lualdap.c:(.text+0xcba): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_bvfree'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: src/lualdap.o:lualdap.c:(.text+0x1232): undefined reference to `ber_free'
src/lualdap.o:lualdap.c:(.text+0x1232): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `ber_free'
collect2: error: ld returned 1 exit status

Error: Build error: Failed compiling module lualdap.so
```

**Comment by lemniscati** [comment]
By the way, is there any reason to avoid modifying `Makefile` and `config`.

**Comment by fperrad** [comment]
@lemniscati,  feedbacks from Cygwin are infrequent, so I asked for other test.

`lber` must be added here : https://github.com/lualdap/lualdap/blob/master/rockspec/lualdap-dev-2.rockspec#L45
```
         libraries = { 'ldap', 'lber' },
```

now, this PR contains your 2 commits, so `Makefile` and `config` will be fixed.

**Comment by lemniscati** [comment]
@fperrad Thank you.

> @lemniscati, feedbacks from Cygwin are infrequent, so I asked for other test.

All right.

> `lber` must be added here : https://github.com/lualdap/lualdap/blob/master/rockspec/lualdap-dev-2.rockspec#L45
> 
> ```
>          libraries = { 'ldap', 'lber' },
> ```

It works with a fixed version of `luarocks` on Cygwin.

> now, this PR contains your 2 commits, and the CI is OK
> so `Makefile` and `config` will be fixed.

Thank you very much.

Regards,
Lem

**Comment by lemniscati** [comment]
For building with `Makefile` on Cygwin, something like following commands will do well with this PR.
```
make LUA=lua5.3 LUA_LIB=-llua5.3
make LUA=lua5.4 LUA_LIB=-llua5.4
```

**Pull request merged**
